### ISSUE TITLE
There is RuntimeError: "addmm_cuda" not implemented for 'Long' when running python3 selor.py  --seed 7 --gpu 0 --dataset yelp --base bert

### ISSUE THREAD

**Issue by joshua-xia** [archon159/SELOR#8]
When I running:
python3 selor.py  --seed 7 --gpu 0 --dataset yelp --base bert

There following error happened:

Traceback (most recent call last):
  File "selor.py", line 171, in <module>
    model = te.train(
  File "/home/joshua/SELOR/selor_utils/train_eval.py", line 382, in train
    classification_dict, roc_auc, pr_auc, valid_loss = eval_epoch(
  File "/home/joshua/SELOR/selor_utils/train_eval.py", line 276, in eval_epoch
    outputs, _, _ = model(
  File "/home/joshua/.custom/cuda11.2.2-cudnn8-devel-ubuntu18.04-py38-jupyter-tensorflow2.6/envs/gpu-xai/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/joshua/SELOR/selor_utils/net.py", line 367, in forward
    atom_prob = self.rs_list[i](h, x_.clone().detach())
  File "/home/joshua/.custom/cuda11.2.2-cudnn8-devel-ubuntu18.04-py38-jupyter-tensorflow2.6/envs/gpu-xai/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/joshua/SELOR/selor_utils/net.py", line 268, in forward
    atom_wsum = torch.mm(prob, self.atom_embedding.detach())
RuntimeError: "addmm_cuda" not implemented for 'Long'

Any suggestion to fix this issue?
Thanks!

**Comment by archon159** [comment]
Hi @joshua-xia, I made a commit to fix the bug.
Try again and please tell me if it works.

**Comment by joshua-xia** [comment]
> Hi @joshua-xia, I made a commit to fix the bug. Try again and please tell me if it works.

Hi @archon159 Thanks for your fix, I will try it and send the feedback.

I find the last evaluation result is saved into "model_explanation.json" file, Would you please upload a "model_explanation.json" file so that we can understand the result of the experiments?

Thanks!

**Comment by archon159** [comment]
@joshua-xia I uploaded the sample result. Please check it.

**Comment by joshua-xia** [comment]
> 

Thanks @archon159, it is very helpful to me, and I also successfully run the all steps and generate the results

**Comment by archon159** [comment]
Great!
